[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "docling>=2.121.0",
  "imagehash>=4.3.2",
  "pillow>=12.2.0",
  "pytest-playwright>=0.7.0",
  "requests>=2.32.3",
]

[project.scripts]
url-decode = "decode_url:main"
image-hashing = "image_hashing:main"

[tool.pyright]
include = ["src/tv_data"]
extraPaths = ["src"]
pythonVersion = "3.13"
typeCheckingMode = "standard"
